params:  
  algo:
    name: a2c_discrete

  model:
    name: discrete_a2c

  network:
    name: actor_critic
    separate: True
    space:
      discrete:
    mlp:
      units: [64,64]
      activation: relu
      initializer:
          name: default
          scale: 2

  load_checkpoint: False
  load_path: path

  config:
      reward_shaper:
        scale_value: 1
      normalize_advantage: True
      gamma: 0.99
      tau: 0.9

      learning_rate: 8e-4
      name: ppo_lunar_discrete
      score_to_win: 300

      grad_norm: 0.5
      entropy_coef: 0.02
      truncate_grads: True
      env_name:  LunarLander-v2
      ppo: true
      e_clip: 0.2
      clip_value: False
      num_actors: 16
      horizon_length: 128
      minibatch_size: 1024
      mini_epochs: 4
      critic_coef: 1
      lr_schedule:  None
      kl_threshold: 0.008
      schedule_type: standard
      normalize_input: False
      seq_length: 4
      bounds_loss_coef: 0

      player:
        render: True
